### ISSUE TITLE
Spike: Point DLPs to CTS V2 API

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/clinical-trials-listing-app#127]
In order to figure out what will break when we switch DLPs to CTS API V2, just update the DLP to point to V2, and document what needs to be done in terms of changing queries, or further investigation/discussion needed on this ticket.

Queries that need to be changed:

- [ ] text here
- [ ] text here
- [ ] text here

Other Items to be considered:

- [ ] text here
- [ ] text here
- [ ] text here

**Comment by alerosad** [comment]
What has been done so far is: Updated API endpoint in index.js and clinicaltrials.js, however, the server did not respond back correctly when updating to v2 of the API.
Current blocker: can't get an api key, in order to test POST method to validate api response

**Comment by alerosad** [comment]
got api key, then tested POST method to see if it returned a valid api response. The returned response was:
{
  "total": 0,
  "data": []
}
when given:

{"current_trial_status":["Active","Approved","Enrolling by Invitation","In Review","Temporarily Closed to Accrual","Temporarily Closed to Accrual and Intervention"],"include":["brief_summary","brief_title","current_trial_status","nci_id","nct_id","sites.org_name","sites.org_country","sites.org_state_or_province","sites.org_city","sites.recruitment_status"],"diseases.nci_thesaurus_concept_id":["C6954","C9372","C9375","C9094","C9370","C9374","C7710","C5967","C9091","C5797","C9373","C9376","C9371","C5116","C5115"],"primary_purpose.primary_purpose_code":"treatment","from":0,"size":25}

It seems that the query formatting may have been changed in v2, or something along those lines. The status code was 200, so it did reach the api and communicate with the api fine

**Comment by alerosad** [comment]
Receiving CORS errors when updating getClinicalTrials.js and index.js in src to v2

**Comment by alerosad** [comment]
Looked through the swagger doc, and then tested the POST method again, and the returned response was the same as above. After doing this, used POSTMAN with the same request headers used in /v1/ for a /v2/ api request, and was returned a 400 error, stating that it was a bad request

**Comment by alerosad** [comment]
I went through and throughly checked that the /v1/ and /v2/ request headers matched and their bodies did as well, but the /v2/ request always returning the CORS error, meaning that something changed in the request headers formatting in the api. With this said, I'm going to see how I can go about finding out what the new request headers should look like.

**Comment by alerosad** [comment]
So the Queries that need to be changed are the request headers, and potentially the request body, depending on what the api dev says

**Comment by blairlearn** [comment]
@alerosad 
> the /v2/ request always returning the CORS error
Do you mean the server returned a message? Or the browser?

We've had problems in the past where the clinicaltrials API didn't respond correctly to the preflight request (the OPTIONS request), at which point the browser will output a console error message and refuse  to send the POST.

If that's what you're seeing, this is actually something which needs to be fixed in the API server.

**Comment by alerosad** [comment]
After speaking with Bryan and messing around, it seems like the reason I was getting a 400 in Postman and curl was on my end. Not sure why my Postman was bugging out, but it was

**Comment by alerosad** [comment]
What needs to be done now is:
- Everywhere in the app that looks for trials, in the return payload, needs to be changed to data.data
- We need to figure out how the implement the new api key request header on the dev side, so an api endpoint must be made for local development
- The mocks will need to be updated to use data.data instead of trials

**Comment by alerosad** [comment]
Intervention is only showing the first page of results when using v2

**Comment by alerosad** [comment]
What needs to be done now is:

- Everywhere in the app that looks for trials, in the return payload, needs to be changed to data.data
- We need to figure out how the implement the new api key request header on the dev side, so an api endpoint must be made for local development
- The mocks will need to be updated to use data.data instead of trials
- Fix Intervention so that it shows all the proper trials
- Fix Manual so that it shows the missing trials

**Comment by alerosad** [comment]
Intervention and Manual are having issues due to the primary_purpose.primary_purpose_code header

**Comment by sarinapadilla** [comment]
Closing this ticket as the update to CTS API v2 has been launched.
